
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: votebox
      POSTGRES_USER: voteuser
      POSTGRES_PASSWORD: votepass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U voteuser -d votebox"]
      interval: 5s
      timeout: 5s
      retries: 5


  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "5000"
    environment:
      DATABASE_URL: postgresql://voteuser:votepass@db:5432/votebox
    networks:
      - appnet


  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - appnet


  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
    driver: bridge
